[workspace]
resolver = "2"

members = [
    "contracts/access-control",
    "contracts/vesting",
    "contracts/multisig",
    "contracts/splitter",
]

[workspace.package]
version = "0.1.0"
authors = ["Stellar Primitives Core Maintainers <maintainers@stellar-primitives.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stellar-primitives/soroban-contracts"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
